### ISSUE TITLE
[Bug]: openai_sensitive_id 获取方法已失效，可否只用api key？

### ISSUE THREAD

**Issue by Ethan-Ming** [iuiaoin/wechat-gptbot#109]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

git pull最新版本之后发现无法启动

终端output如下

### Relevant log output

```shell
(arco) PS E:\LLaMs\Wechat_auto-reply\new\wechat-gptbot> python app.py
Traceback (most recent call last):
  File "E:\LLaMs\Wechat_auto-reply\new\wechat-gptbot\app.py", line 1, in <module>
    from channel.wechat import WeChatChannel
  File "E:\LLaMs\Wechat_auto-reply\new\wechat-gptbot\channel\wechat.py", line 9, in <module>
    from bot.bot import Bot
  File "E:\LLaMs\Wechat_auto-reply\new\wechat-gptbot\bot\bot.py", line 1, in <module>
    import litellm
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\__init__.py", line 75, in <module>
    from .utils import client, logging, exception_type, get_optional_params, modify_integration
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 8, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\load.py", line 117, in load_tiktoken_bpe
    return {
  File "C:\Users\Ethan\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\load.py", line 117, in <dictcomp>
    return {
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by QAbot-zh** [comment]
你报的错跟api key没关系啊，检查下litellm和tiktoken版本和项目要求的版本是否一致

**Comment by Ethan-Ming** [comment]
litellm版本是正确的， tiktoken 是0.4.0
干净的Conda环境

(webot) PS E:\LLaMs\Wechat_auto-reply\wechat-gptbot> pip show tiktoken
Name: tiktoken
Version: 0.4.0

(webot) PS E:\LLaMs\Wechat_auto-reply\wechat-gptbot> pip show litellm
Name: litellm
Version: 0.1.365
