### ISSUE TITLE
failed to start 

### ISSUE THREAD

**Issue by poiuyb** [iuiaoin/wechat-gptbot#112]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

[ERROR][2024-02-13 12:09:38][app.py:22] - App startup failed!
[ERROR][2024-02-13 12:09:38][app.py:23] - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Gne\Desktop\wechat-gptbot-main\app.py", line 11, in <module>
    load_config()
  File "C:\Users\Gne\Desktop\wechat-gptbot-main\config.py", line 16, in load_config
    config = json.loads(config_str)
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by QAbot-zh** [comment]
你的config.json有问题

**Comment by poiuyb** [comment]
那个文件问题解决了
启动后这个问题是openai api url 不对还是梯子的问题

[INFO][2024-02-15 23:22:19][wechat.py:40] - App startup successfully!
[ERROR][2024-02-15 23:22:21][wechat.py:218] - [Websocket] Error: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
[ERROR][2024-02-15 23:22:21][wechat.py:218] - [Websocket] Error: WeChatChannel.on_close() takes 2 positional arguments but 4 were given

**Comment by poiuyb** [comment]
这个是梯子问题还是 api url的问题我用的是这个https://api.chatgpt.com/v1/generate

[ERROR][2024-02-15 23:29:21][api.py:46] - Get personal info failed!
[ERROR][2024-02-15 23:29:21][api.py:47] - HTTPConnectionPool(host='127.0.0.1', port=5555): Max retries exceeded with url: //api/get_personal_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000260BCD544C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

**Comment by QAbot-zh** [comment]
> 这个是梯子问题还是 api url的问题我用的是这个https://api.chatgpt.com/v1/generate
> 
> [ERROR][2024-02-15 23:29:21][api.py:46] - Get personal info failed! [ERROR][2024-02-15 23:29:21][api.py:47] - HTTPConnectionPool(host='127.0.0.1', port=5555): Max retries exceeded with url: //api/get_personal_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000260BCD544C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')) Traceback (most recent call last): File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn conn = connection.create_connection( File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection raise err File "C:\Users\Gne\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection sock.connect(sa) ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

这个报错像是你的dll没有注入成功，所以程序连接不到微信。你按照注入操作执行了吗，是否有看到inject success ？

**Comment by poiuyb** [comment]
注入过了我在试下看看

**Comment by poiuyb** [comment]
成功了但是gpt回复不能连接到服务是梯子的问题么

**Comment by poiuyb** [comment]
成功启动了但是gpt回复I cannot connect the server, please check the network and try again 是梯子的问题么
[INFO][2024-02-16 00:01:08][chatgpt.py:26] - [ChatGPTBot] Query=可以教一下我怎么学习java吗
[WARNING][2024-02-16 00:01:14][chatgpt.py:76] - [ChatGPTBot] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.chatgpt.com', port=443): Max retries exceeded with url: /v1/generate/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029D25B73880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

**Comment by QAbot-zh** [comment]
> 成功启动了但是gpt回复I cannot connect the server, please check the network and try again 是梯子的问题么 [INFO][2024-02-16 00:01:08][chatgpt.py:26] - [ChatGPTBot] Query=可以教一下我怎么学习java吗 [WARNING][2024-02-16 00:01:14][chatgpt.py:76] - [ChatGPTBot] APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.chatgpt.com', port=443): Max retries exceeded with url: /v1/generate/chat/completions (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000029D25B73880>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))

这是你的反代地址吗？连接超时既可能是url服务有问题，也可能是梯子问题。如果这是你的反代地址，那应该不加generate；如果是中转站买的key，那就参考中转站的站点配置。

**Comment by poiuyb** [comment]
不加generate也不行 那个 "openai_api_base"用的是这个"https://api.chatgpt.com/v1",

**Comment by QAbot-zh** [comment]
> 不加generate也不行 那个 "openai_api_base"用的是这个"https://api.chatgpt.com/v1",

测了一下，是那个反代地址已经失效了。你如果是官方的key，能魔法，你就直接用官方的地址："https://api.openai.com/v1"，如果不想架梯子，可以用我的反代地址：【】。

**Comment by poiuyb** [comment]
这个是啥情况
[INFO][2024-02-16 19:51:25][chatgpt.py:26] - [ChatGPTBot] Query=可以教我java吗
[WARNING][2024-02-16 19:51:25][chatgpt.py:73] - [ChatGPTBot] RateLimitError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
[INFO][2024-02-16 19:51:25][chatgpt.py:33] - [ChatGPTBot] Response=Ask too frequently, please try again in 20s
[INFO][2024-02-16 19:51:26][wechat.py:83] - message sent successfully

**Comment by QAbot-zh** [comment]
key 没钱了或者过期了
