### ISSUE TITLE
[Bug]: Get personal info failed!

### ISSUE THREAD

**Issue by 1850VV** [iuiaoin/wechat-gptbot#33]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.10

### Issue description

大佬，我启动的时候发生这个报错
Traceback (most recent call last):
  File "E:\gpt\wechat-gptbot\channel\wechat.py", line 195, in get_personal_info
    response = self.fetch(uri, data)
  File "E:\gpt\wechat-gptbot\channel\wechat.py", line 231, in fetch
    response = requests.post(url, json={"para": base_data}, timeout=5)
  File "C:\Users\NORTHSEA\.virtualenvs\wechat-gptbot-CoTc_QE1\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\NORTHSEA\.virtualenvs\wechat-gptbot-CoTc_QE1\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\NORTHSEA\.virtualenvs\wechat-gptbot-CoTc_QE1\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\NORTHSEA\.virtualenvs\wechat-gptbot-CoTc_QE1\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\NORTHSEA\.virtualenvs\wechat-gptbot-CoTc_QE1\lib\site-packages\requests\adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5555): Max retries exceeded with url: //api/get_personal_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000213D71783D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[INFO][2023-06-18 14:47:01][wechat.py:34] - App startup successfully!
[ERROR][2023-06-18 14:47:03][wechat.py:241] - [Websocket] Error: [WinError 10061] 由于目标计算机积极拒绝，无法连接。
[ERROR][2023-06-18 14:47:03][wechat.py:241] - [Websocket] Error: WeChatChannel.on_close() takes 2 positional arguments but 4 were given

Process finished with exit code 0
请问该如何解决？

**Comment by iuiaoin** [comment]
你在登录微信之后运行wechat-injector注入dll了吗？需要注入成功之后再运行app.py

**Comment by 10r4** [comment]
网络问题
