### ISSUE TITLE
failed to start[Bug]: 

### ISSUE THREAD

**Issue by drc11** [iuiaoin/wechat-gptbot#98]
### Search for answers in existing issues

- [X] I have searched issues, there is no issue related to the problem I encountered

### Python version

python 3.8

### Issue description

F:\wechat-gptbot>python app.py
[ERROR][2023-11-08 01:56:51][app.py:22] - App startup failed!
[ERROR][2023-11-08 01:56:51][app.py:23] - Expecting ':' delimiter: line 2 column 128 (char 129)
Traceback (most recent call last):
  File "F:\wechat-gptbot\app.py", line 11, in <module>
    load_config()
  File "F:\wechat-gptbot\config.py", line 16, in load_config
    config = json.loads(config_str)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 2 column 128 (char 129)

**Comment by QAbot-zh** [comment]
你的config.json有问题，第二行缺少引号
